version: "3.9"

services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - PG_LINK=${PG_LINK}
      - PG_PASS=${PG_PASS}
      - PG_USER=${PG_USER}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - SHOP_ID=${SHOP_ID}
      - SHOP_SECRET=${SHOP_SECRET}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_IP=${SERVER_IP}

  frontend:
    build: ./client
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    depends_on:
      - backend
