spring:
  application:
    name: server
  mail:
    host: smtp.timeweb.ru
    username: no-reply@mwps.ru
    password: GtE64kX(DT\~3|
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    url: jdbc:postgresql://localhost:30070/data
    password: admin
    username: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081
settings:
  security:
    allowed-origins: http://localhost:5173/